app/models/Producto.php
<?php

namespace app\models;

use app\models\Marca;
use app\models\TipoProducto;
use app\models\Proveedor;
use app\models\TipoPresentacion;
use app\vendor\base\BaseActiveRecord;

use Yii;

/**
 * This is the model class for table "producto".
 *
 * @property integer $IdProducto
 * @property integer $IdProveedor
 * @property integer $IdMarca
 * @property integer $IdTipoProducto
 * @property integer $IdTipoPresentacion
 * @property string $CodBarra
 * @property string $Descripcion
 * @property string $CantPresentacion
 * @property TipoProducto $idTipoProducto

 */
 
class Producto extends BaseActiveRecord       
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'producto';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'IdMarca','IdTipoProducto','IdTipoPresentacion', 'CodBarra', 'Descripcion', 'CantPresentacion'], 'required'],
            [['IdProducto', 'IdProveedor', 'IdMarca', 'IdTipoProducto','IdTipoPresentacion','CantPresentacion'], 'integer'],
            [['CodBarra'], 'string', 'max' => 50],
            [['Descripcion'], 'string', 'max' => 150],
            [['CodBarra'], 'unique', 'targetAttribute' => ['CodBarra'], 'message' => 'El Codigo ingresado ya existe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'IdProducto' => 'Producto',
            'IdProveedor' => 'Proveedor',
            'IdMarca' => 'Marca',
            'IdTipoProducto' => 'Tipo Producto',
            'IdTipoPresentacion' => 'Tipo Presentacion',
            'CodBarra' => 'Codigo Barra',
            'Descripcion' => 'Descripcion',
            'TipoProductos'=>'Tipo Producto',
            'Marcas'=>'Marcas',
            'Proveedores'=>'Proveedores',
            'CantPresentacion' => 'Cantidad Presentacion',           
        ];
    }

    public function getIdProveedor()
    {
        return $this->hasOne(Proveedor::className(), ['IdProveedor' => 'IdProveedor']);
    }
     public function getProveedores()
    {
        return $this->idProveedor->RazonSocial;
    }
    public function getIdMarca()
    {
        return $this->hasOne(Marca::className(), ['IdMarca' => 'IdMarca']);
    }

    public function getMarcas()
    {
        return $this->idMarca->Marca;
    }

    public function getIdTipoProducto()
    {
        return $this->hasOne(TipoProducto::className(), ['IdTipoProducto' => 'IdTipoProducto']);
    }
    
    public function getTipoProductos()
    {
       // return $this->idTipoProducto->TipoProducto;
        $return = "";
        $tipoProducto = Tipoproducto::findOne($this->IdTipoProducto);
        return $tipoProducto->TipoProducto;
    }

     public function getIdTipoPresentacion()
    {
        return $this->hasOne(TipoPresentacion::className(), ['IdTipoPresentacion' => 'IdTipoPresentacion']);
    }
    
    public function getTipoPresentacion()
    {
        return $this->idTipoPresentacion->Descripcion;
    }
}

app/controllers/ProductoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Producto;
use app\models\ProductoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\vendor\base\BaseController;
/**
 * ProductoController implements the CRUD actions for Producto model.
 */
class ProductoController extends BaseController
{
    /**
     * Lists all Producto models.
     * @return mixed
     */
    public function actionIndex($codBarra=null)
    {
        $searchModel = new ProductoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$codBarra);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Producto model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Producto model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Producto();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
           Yii::$app->session->setFlash('success', 'El registro ha sido guardado!');
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }

    }

    /**
     * Updates an existing Producto model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
             Yii::$app->session->setFlash('success', 'El registro ha sido modificado!');
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Producto model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
         Yii::$app->session->setFlash('success','El registro ha sido eliminado!'); 
        return $this->redirect(['index']);
    }

    /**
     * Finds the Producto model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Producto the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Producto::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

app/views/producto/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Proveedor;
use app\models\Marca;
use app\models\TipoProducto;
use app\models\TipoPresentacion;
/* @var $this yii\web\View */
/* @var $model app\models\Producto */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="producto-form">


    <?php $form = ActiveForm::begin(['class'=>'form-inline form-group-xs'],['fieldConfig' => ['validateOnSubmit'=>false]]); ?>

    <?= $form->errorSummary($model) ?>
    

<div class="form-group form-group-xs">
    <label class="col-xs-3 control-label" for="CodBarra">Codigo Barra</label>
    <div class="col-xs-2">  
            <?= $form->field($model, 'CodBarra')->textInput(['maxlength' => true],['class' => 'form-control'])->label(false) ?>
    </div>       
</div>
<div class="row"></div>

<div class="form-group form-group-xs">
    <label class="col-xs-3 control-label" for="Descripcion">Descripcion</label>
    <div class="col-xs-4">  
            <?= $form->field($model, 'Descripcion')->textInput(['maxlength' => true],['class' => 'form-control'])->label(false) ?>
    </div>       
</div>
<div class="row"></div>
    
<div class="form-group form-group-xs">
    <label class="col-xs-3 control-label" for="IdProveedor">Proveedor</label>
    <div class="col-xs-3">  
            <?= $form->field($model, 'IdProveedor')->dropDownList(ArrayHelper::map(Proveedor::find()->all(),'IdProveedor','RazonSocial'),['class' => 'form-control'])->label(false) ?>
    </div>
    <span class="input-group-btn">
         <?= Html::a('+', Url::to( ['proveedor/create','env' => 'producto']), ['class' => 'btn btn-success']) ?>
    </span>
</div>
<div class="row"></div>

<div class="form-group form-group-xs">
    <label class="col-xs-3 control-label" for="IdMarca">Marca</label>
    <div class="col-xs-3">
           <?= $form->field($model, 'IdMarca')->dropDownList(ArrayHelper::map(Marca::find()->all(),'IdMarca','Marca'),['class' => 'form-control'])->label(false) ?>
    </div>
    <span class="input-group-btn">
            <?= Html::a('+', Url::to( ['marca/create','env' => 'producto']), ['class' => 'btn btn-success']) ?>
    </span>
</div>
<div class="row"></div>

<div class="form-group form-group-xs">
    <label class="col-xs-3 control-label" for="IdTipoProducto">Tipo Producto</label>
    <div class="col-xs-3">  
            <?= $form->field($model, 'IdTipoProducto')->dropDownList(ArrayHelper::map(TipoProducto::find()->all(),'IdTipoProducto','TipoProducto'),['class' => 'form-control'])->label(false) ?>
    </div>
    <span class="input-group-btn">
        <?= Html::a('+', Url::to( ['tipo-producto/create','env' => 'producto']), ['class' => 'btn btn-success']) ?>
    </span>
</div>
<div class="row"></div>

<div class="form-group form-group-xs">
    <label class="col-sm-3 control-label" for="IdTipoPresentacion">Tipo Presentaci&oacuten</label>
    <div class="col-sm-3">
           <?= $form->field($model, 'IdTipoPresentacion')->dropDownList(ArrayHelper::map(TipoPresentacion::find()->all(),'IdTipoPresentacion','Descripcion'),['class' => 'form-control'])->label(false) ?>
    </div>      
</div>
<div class="row"></div>

 <div class="form-group form-group-xs">
    <label class="col-xs-3 control-label" for="CantPresentacion">Cant. Presentaci&oacuten</label>
    <div class="col-xs-2">
       <?= $form->field($model, 'CantPresentacion')->textInput(['maxlength' => true],['class' => 'form-control'])->label(false)?>
    </div>
 </div>
<div class="row"></div>

<div class="form-group form-group-sm">
        <?= Html::submitButton($model->isNewRecord ? 'Guardar' : 'Guardar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a('Cancelar', Url::to( ['producto/index']), ['class' => 'btn btn-danger', 'data-confirm' => '¿Desea cancelar los cambios?']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/producto/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProductoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="producto-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'IdProducto') ?>

    <?= $form->field($model, 'IdProveedor') ?>

    <?= $form->field($model, 'IdMarca') ?>

    <?= $form->field($model, 'IdTipoProducto') ?>

    <?= $form->field($model, 'CodBarra') ?>

    <?php // echo $form->field($model, 'Descripcion') ?>

    <?php // echo $form->field($model, 'PresCompra') ?>

    <?php // echo $form->field($model, 'PresVenta') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/producto/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Producto */

$this->title = 'Agregar Producto';
$this->params['breadcrumbs'][] = ['label' => 'Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="producto-create">
    <div class="row">
        <div class="col-lg-4">
            
        </div>
    </div>
	<div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header"><?= Html::encode($this->title) ?></h3>
                    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
                </div>
                <!-- /.col-lg-12 -->
    </div>

    

</div>

app/views/producto/index.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\Proveedor;
use app\models\Marca;
use app\models\TipoProducto;
use app\models\TipoPresentacion;
use kartik\export\ExportMenu;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Productos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="producto-index">
 <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header"><?= Html::encode($this->title) ?></h3>
                </div>
                <!-- /.col-lg-12 -->
    </div>
    <p>
        <?= Html::a('Agregar Producto', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    
    <?php
    $gridColumns = [
             'CodBarra',
             'Descripcion',
             [
                'attribute' => 'Proveedores',
                 'filter' => ArrayHelper::map(Proveedor::find()->orderBy(['RazonSocial'=>SORT_ASC])->all(), 'IdProveedor', 'RazonSocial'),                
             ],             
             [
                'attribute' => 'Marcas',
                'filter' => ArrayHelper::map(Marca::find()->orderBy(['Marca'=>SORT_ASC])->all(), 'IdMarca', 'Marca'),
             ],
             [
                'attribute' => 'TipoProductos',
                'filter' => ArrayHelper::map(TipoProducto::find()->orderBy(['TipoProducto'=>SORT_ASC])->all(), 'IdTipoProducto', 'TipoProducto'),
             ],
            // 'descripcion',
            ['class' => 'yii\grid\ActionColumn', 'template' => '{update} {delete}',]
        ];
    
    echo GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'responsive' => true,
                'hover' => true,
                'autoXlFormat' => true,
                'panel' => [
                    'type' => GridView::TYPE_DEFAULT,
                    'footer' => false
                ],
                'toolbar' => [
                    '{export}', '{toggleData}'
                ],
                'columns' => $gridColumns,
                'exportConfig' => [
                    GridView::EXCEL => [
                        'filename' => 'productos_' . date('YmdHis'),
                        'options' => ['title' => 'Microsoft Excel 95+'],
                        'mime' => 'application/vnd.ms-excel',
                    ],
                    GridView::PDF => [
                        'filename' => 'productos_' . date('YmdHis'),
                        'mime' => 'application/pdf',
                        'config' => [
                            'format' => 'A4-P',
                            'destination' => 'I',
                            'mode' => 'utf-8',
                            'methods' => [
                                'SetHTMLHeader' => '<div style="text-aling: left; font-weight: bold;display:inline-block">' . Html::encode($this->title) . '</div>',
                                'SetFooter' => ['{PAGENO}'],
                            ],
                            'cssInline' => '.progress-bar,.progress-bar-warning{background-color:#fff !important;color:#333}'
                        ],
                        'showPageSummary' => FALSE,
                        'showCaption' => FALSE,
                    ]
                ],
                'export' => [
                    'fontAwesome' => false,
                    'showConfirmAlert' => false,
                    'label' => 'Exportar',
                    'target' => GridView::TARGET_BLANK,
                ],
            ]);
            
            
            
        ?>

    

</div>

app/views/producto/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Producto */

$this->title = 'Editar Producto: ' . ' ' . $model->Descripcion;
$this->params['breadcrumbs'][] = ['label' => 'Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->IdProducto, 'url' => ['view', 'id' => $model->IdProducto]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="producto-update">

     <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header"><?= Html::encode($this->title) ?></h3>
                </div>
                <!-- /.col-lg-12 -->
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/views/producto/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Producto */

$this->title = $model->IdProducto;
$this->params['breadcrumbs'][] = ['label' => 'Productos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="producto-view">

    <h2><?= Html::encode($this->title) ?></h2>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->IdProducto], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->IdProducto], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Seguro desea eliminar este item ?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'IdProducto',
            'IdProveedor',
            'IdMarca',
            'IdTipoProducto',
            'CodBarra',
            'Descripcion',
            'PresCompra',
            'PresVenta',
        ],
    ]) ?>

</div>