app/models/Localidad.php
<?php

namespace app\models;

use Yii;
use app\vendor\base\BaseActiveRecord;

/**
 * This is the model class for table "localidad".
 *
 * @property string $IdLocalidad
 * @property string $Nombre
 * @property string $IdProvincia
 * @property string $CodigoPostal
 *
 * @property Provincia $idProvincia
 */
class Localidad extends BaseActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'localidad';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Nombre', 'IdProvincia'], 'required'],
            [['IdProvincia'], 'integer'],
            [['Nombre'], 'string', 'max' => 100],
            [['CodigoPostal'], 'string', 'max' => 8]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'IdLocalidad' => 'Id Localidad',
            'Nombre' => 'Nombre',
            'IdProvincia' => 'Provincia',
            'CodigoPostal' => 'Código Postal',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdProvincia()
    {
        return $this->hasOne(Provincia::className(), ['IdProvincia' => 'IdProvincia']);
    }
    
    public function getProvincia(){
        return $this->idProvincia->Nombre;
    }
}

app/controllers/LocalidadController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Localidad;
use app\models\LocalidadSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\vendor\base\BaseController;

/**
 * LocalidadController implements the CRUD actions for Localidad model.
 */
class LocalidadController extends BaseController {

    /**
     * Lists all Localidad models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new LocalidadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Localidad model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Localidad();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'El registro ha sido guardado!');
            return $this->redirect(['index']);
        } else {

            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Localidad model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'El registro ha sido modificado!');
            return $this->redirect(['index']);
        } else {
          
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Localidad model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {

         try {
            $this->findModel($id)->delete();
        } catch (yii\db\IntegrityException $e) {
            if($e->getCode() == 23000){
                Yii::$app->session->setFlash('danger',Yii::t('app', 'El registro no se puede eliminar, existe un registro relacionado'));
                return $this->redirect(['index']);
            }
        }

        Yii::$app->session->setFlash('success',Yii::t('app', 'El registro ha sido eliminado!'));      
        return $this->redirect(['index']);
    }

    /**
     * Finds the Localidad model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Localidad the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Localidad::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

app/views/localidad/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Provincia;

/* @var $this yii\web\View */
/* @var $model app\models\Localidad */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="localidad-form">

    <?php $form = ActiveForm::begin(['fieldConfig' => ['template' => "<div class='row'><div class='col-xs-2'>{label}</div><div class='col-xs-4'>{input}</div></div>"],'validateOnSubmit'=>false]); ?>

    <?= $form->errorSummary($model) ?>

    <?= $form->field($model, 'Nombre')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'IdProvincia')->dropDownList(ArrayHelper::map(Provincia::find()->all(),'IdProvincia','Nombre')) ?>

    <?= $form->field($model, 'CodigoPostal',['template' => "<div class='row'><div class='col-xs-2'>{label}</div><div class='col-xs-2'>{input}</div></div>"] )->textInput(['maxlength' => 8]) ?>
    
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Guardar' : 'Guardar', ['class' =>=> $model->isNewRecord ? 'btn btn-success', 'data-confirm' => '¿Desea guardar los cambios?']) ?>
        <?= Html::a('Cancelar', Url::toRoute('localidad/index'), ['class' => 'btn btn-danger', 'data-confirm' => '¿Desea cancelar los cambios?']) ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/localidad/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LocalidadSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="localidad-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'IdLocalidad') ?>

    <?= $form->field($model, 'Nombre') ?>

    <?= $form->field($model, 'IdProvincia') ?>

    <?= $form->field($model, 'CodigoPostal') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/localidad/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Localidad */

$this->title = 'Agregar localidad';
$this->params['breadcrumbs'][] = ['label' => 'Localidades', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="localidad-create">

    <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header"><?= Html::encode($this->title) ?></h3>
                </div>
                <!-- /.col-lg-12 -->
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/views/localidad/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\Provincia;
/* @var $this yii\web\View */
/* @var $searchModel app\models\LocalidadSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Localidades';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="localidad-index">

    <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header"><?= Html::encode($this->title) ?></h3>
                </div>
                <!-- /.col-lg-12 -->
    </div>
    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Agregar', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => 
        [
            'Nombre', 
            ['attribute' => 'Provincia','filter' => ArrayHelper::map(Provincia::find()->orderBy(['Nombre'=>SORT_ASC])->all(), 'IdProvincia', 'Nombre'),],
            'CodigoPostal',
            ['class' => 'yii\grid\ActionColumn','template' => '{update} {delete}',]
        ],
    ]); 

?>
</div>

app/views/localidad/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Localidad */

$this->title = 'Editar localidad';
?>
<div class="localidad-update">

    <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header"><?= Html::encode($this->title) ?></h3>
                </div>
                <!-- /.col-lg-12 -->
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>